-- ============================================================================
-- SQL MASTER SCHEMA: E-COMMERCE PROFESIONAL Y ESCALABLE (SUPABASE / POSTGRESQL)
-- Diseñado por Christian @ Ventas Juem
-- ============================================================================
-- Este script define la arquitectura óptima, segura y preparada para producción.
-- Incluye Integridad Referencial, Soft-Deletes, Historiales, Variantes Dinámicas,
-- Índices de Rendimiento, RLS y Triggers para auditoría.
-- ============================================================================

-- Habilitar extensión UUID para identificadores seguros si no está activa
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 0. TABLA DE CONFIGURACIÓN GLOBAL (TIENDA CORE)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.shop_state (
    id VARCHAR(50) PRIMARY KEY,
    state JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 1. ROLES Y USUARIOS (CLIENTES / PERSONAL)
-- ==========================================

-- Tabla de Roles
CREATE TABLE IF NOT EXISTS public.user_roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL, -- 'admin', 'vendedor', 'cliente'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Usuarios Centrales (Clientes y Administradores)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(50),
    role_id INTEGER REFERENCES public.user_roles(id) DEFAULT 3, -- 3 = cliente
    profile_image TEXT,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Credenciales Administrativas (Compatibilidad y Backoffice)
CREATE TABLE IF NOT EXISTS public.admin_credentials (
    username VARCHAR(100) PRIMARY KEY,
    password_hash TEXT NOT NULL,
    session_token TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Direcciones de Entrega Múltiples (user_addresses)
CREATE TABLE IF NOT EXISTS public.user_addresses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    alias VARCHAR(50) DEFAULT 'Casa', -- 'Trabajo', 'Casa'
    street VARCHAR(255) NOT NULL,
    number VARCHAR(20) NOT NULL,
    apartment VARCHAR(20),
    city VARCHAR(100) NOT NULL,
    state_province VARCHAR(100) NOT NULL, -- Provincia / Estado
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) DEFAULT 'Argentina',
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. MARCAS, CATEGORÍAS Y CATALOGACIÓN
-- ==========================================

-- Tabla de Marcas (brands)
CREATE TABLE IF NOT EXISTS public.brands (
    id VARCHAR(100) PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT,
    description TEXT,
    slug VARCHAR(150) UNIQUE NOT NULL,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Categorías (Organización principal jerárquica)
CREATE TABLE IF NOT EXISTS public.categories (
    id VARCHAR(100) PRIMARY KEY,
    nombre TEXT NOT NULL,
    icono VARCHAR(100) DEFAULT 'Shirt',
    orden INTEGER DEFAULT 1,
    active BOOLEAN DEFAULT true,
    seo_title VARCHAR(150),
    seo_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Subcategorías (Nivel secundario)
CREATE TABLE IF NOT EXISTS public.subcategories (
    id VARCHAR(100) PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria_id VARCHAR(100) REFERENCES public.categories(id) ON DELETE CASCADE,
    active BOOLEAN DEFAULT true,
    seo_title VARCHAR(150),
    seo_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Etiquetas/Tags para búsquedas inteligentes
CREATE TABLE IF NOT EXISTS public.tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL
);

-- ==========================================
-- 3. PRODUCTOS Y CONTROL DE INVENTARIO
-- ==========================================

-- Tabla Maestra de Productos
CREATE TABLE IF NOT EXISTS public.products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Mantiene compatibilidad con tu server.ts actual
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    original_price NUMERIC(10, 2), -- Precio tachado
    stock INTEGER NOT NULL DEFAULT 0, -- Stock consolidado
    category TEXT, -- Tag general de compatibilidad
    categoria_id VARCHAR(100) REFERENCES public.categories(id) ON DELETE SET NULL,
    subcategoria_id VARCHAR(100) REFERENCES public.subcategories(id) ON DELETE SET NULL,
    brand_id VARCHAR(100) REFERENCES public.brands(id) ON DELETE SET NULL,
    featured BOOLEAN DEFAULT false,
    paused BOOLEAN DEFAULT false, -- Pausado/sin mostrar temporalmente
    active BOOLEAN DEFAULT true,  -- Soft delete
    description TEXT,
    image_url TEXT, -- Imagen principal por defecto
    slug VARCHAR(255), -- Para URLs SEO amigables
    meta_title VARCHAR(150),
    meta_description TEXT,
    sizes TEXT[] DEFAULT '{}', -- Array compatible (Retrocompatibilidad)
    colors TEXT[] DEFAULT '{}', -- Array compatible (Retrocompatibilidad)
    
    -- Funcionalidades avanzadas e integraciones
    is_3d BOOLEAN DEFAULT false,
    hours_per_unit NUMERIC(10, 2),
    size_chart_enabled BOOLEAN DEFAULT true,
    size_chart_show_superior BOOLEAN DEFAULT false,
    size_chart_show_inferior BOOLEAN DEFAULT false,
    size_chart_show_calzado BOOLEAN DEFAULT false,
    size_chart_show_recommender BOOLEAN DEFAULT false,
    size_chart_data JSONB,
    consult_only BOOLEAN DEFAULT false,
    categorias_adicionales TEXT[] DEFAULT '{}',
    subcategorias_adicionales TEXT[] DEFAULT '{}',
    codigo VARCHAR(100),
    precio_compra NUMERIC(10, 2) DEFAULT 0.00,
    precio_con_40 NUMERIC(10, 2) DEFAULT 0.00,
    comision_ml NUMERIC(10, 2) DEFAULT 0.00,
    precio_venta_ml NUMERIC(10, 2) DEFAULT 0.00,
    precio_web NUMERIC(10, 2) DEFAULT 0.00,
    descuento_porcentaje NUMERIC(10, 2) DEFAULT 0.00,
    stock_pinamar INTEGER DEFAULT 0,
    stock_montevideo INTEGER DEFAULT 0,
    is_combo BOOLEAN DEFAULT false,
    combo_components JSONB DEFAULT '[]',

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT price_positive CHECK (price >= 0),
    CONSTRAINT stock_non_negative CHECK (stock >= 0)
);

-- Tabla de Múltiples Imágenes por Producto (Soporta múltiples espectáculos visuales por artículo)
CREATE TABLE IF NOT EXISTS public.product_images (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    alt_text VARCHAR(150),
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Variantes Avanzadas (Talle, Color, Combinaciones y stocks específicos)
CREATE TABLE IF NOT EXISTS public.product_variants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    sku VARCHAR(100) UNIQUE, -- Código de barra/identificación único
    size_value VARCHAR(50), -- Ej. 'M', 'L', 'XL' o '42'
    color_name VARCHAR(50), -- Ej. 'Azul', 'Rojo'
    color_code VARCHAR(20), -- Ej. '#2563eb' para la interfaz cromática
    additional_price NUMERIC(10, 2) DEFAULT 0.00, -- Suma al precio base
    stock INTEGER NOT NULL DEFAULT 0, -- Stock exacto de esta combinación
    
    -- Nuevas columnas de integración y depósitos
    image_url TEXT,
    price NUMERIC(10, 2),
    stock_pinamar INTEGER DEFAULT 0,
    stock_montevideo INTEGER DEFAULT 0,

    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Etiquetas Asociadas al Producto
CREATE TABLE IF NOT EXISTS public.product_tags_mapping (
    product_id INTEGER REFERENCES public.products(id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);

-- Historial de Movimientos de Inventario (inventory_movements)
CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id INTEGER REFERENCES public.products(id) ON DELETE SET NULL,
    variant_id UUID REFERENCES public.product_variants(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL, -- Positivo para entradas (compra), Negativo para salidas (venta o merma)
    movement_type VARCHAR(50) NOT NULL, -- 'compra', 'venta', 'devolucion', 'ajuste_manual', 'merma'
    description TEXT, -- Motivo o ID del pedido asociado
    created_by VARCHAR(100), -- ID del admin o sistema
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 4. CUPONES, CARRITOS Y VENTAS
-- ==========================================

-- Tabla de Cupones de Descuento
CREATE TABLE IF NOT EXISTS public.coupons (
    code VARCHAR(100) PRIMARY KEY,
    discount_percent INTEGER NOT NULL CHECK (discount_percent BETWEEN 1 AND 100),
    expiration_date TIMESTAMPTZ,
    active BOOLEAN DEFAULT true,
    min_purchase_amount NUMERIC(10, 2) DEFAULT 0.00,
    usage_limit INTEGER DEFAULT NULL,
    usage_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Carritos Guardados / Abandonados (saved_carts)
CREATE TABLE IF NOT EXISTS public.saved_carts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    session_token VARCHAR(255), -- Para clientes anónimos
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Items del Carritos Guardados
CREATE TABLE IF NOT EXISTS public.cart_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    cart_id UUID NOT NULL REFERENCES public.saved_carts(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    variant_id UUID REFERENCES public.product_variants(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0)
) ;

-- Tabla de Órdenes Master (Pedidos Realizados)
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    customer_email VARCHAR(255) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_phone VARCHAR(50),
    
    -- Totales y Cupones
    subtotal NUMERIC(10, 2) NOT NULL,
    discount_amount NUMERIC(10, 2) DEFAULT 0.00,
    shipping_cost NUMERIC(10, 2) DEFAULT 0.00,
    total NUMERIC(10, 2) NOT NULL,
    applied_coupon_code VARCHAR(100) REFERENCES public.coupons(code) ON DELETE SET NULL,
    
    -- Estado global de la venta
    current_status VARCHAR(50) NOT NULL DEFAULT 'pnd_pago', -- 'pendiente', 'pagado', 'enviado', 'entregado', 'cancelado'
    
    -- Nuevos campos de gestión de stock, depósito y canal
    payment_method VARCHAR(50),
    deposito_origen VARCHAR(50),
    canal VARCHAR(50),
    bypass_stock_deduction BOOLEAN DEFAULT false,

    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Detalle de Pedidos (Líneas de Compra/Items de Órdenes)
CREATE TABLE IF NOT EXISTS public.order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES public.products(id) ON DELETE SET NULL,
    variant_id UUID REFERENCES public.product_variants(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL, -- Resguardo del nombre original al momento de la venta
    sku VARCHAR(100),
    size_selected VARCHAR(50),
    color_selected VARCHAR(50),
    unit_price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    total_price NUMERIC(10, 2) NOT NULL
);

-- Historial de Estados del Pedido (order_status_history)
CREATE TABLE IF NOT EXISTS public.order_status_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    previous_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    notified_customer BOOLEAN DEFAULT false,
    comment TEXT, -- Ej. 'Despachado por Andreani' o 'Medio de pago Verificado'
    created_by VARCHAR(100) DEFAULT 'system',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 5. PAGOS, ENVÍOS Y VALORACIONES
-- ==========================================

-- Tabla de Pagos
CREATE TABLE IF NOT EXISTS public.payments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,
    payment_method VARCHAR(50) NOT NULL, -- 'mercado_pago', 'transferencia', 'tarjeta_credito'
    status VARCHAR(50) NOT NULL, -- 'aprobado', 'pendiente', 'rechazado'
    transaction_id VARCHAR(255), -- Código de transacción de la pasarela de pagos
    amount_paid NUMERIC(10, 2) NOT NULL,
    voucher_url TEXT, -- Comprobante de transferencia subido por el cliente
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Envíos y Seguimientos
CREATE TABLE IF NOT EXISTS public.shippings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    shipping_method VARCHAR(100) NOT NULL, -- 'correo_argentino', 'andreani', 'retiro_local'
    tracking_number VARCHAR(100), -- Número de seguimiento
    tracking_url TEXT, -- Link para rastrear
    delivery_address TEXT NOT NULL, -- Texto completo de la dirección elegida
    cost NUMERIC(10, 2) DEFAULT 0.00,
    estimated_delivery_date TIMESTAMPTZ,
    status VARCHAR(50) DEFAULT 'recolectando', -- 'recolectando', 'en_viaje', 'entregado', 'incidencia'
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Opiniones de Clientes (reviews)
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    customer_name VARCHAR(100) NOT NULL, -- Respaldo para reviews anónimas/sin login
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    approved BOOLEAN DEFAULT false, -- Moderación de opinión
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 6. AUDITORÍA, BANNERS Y NOTIFICACIONES
-- ==========================================

-- Tabla de Historial de Auditoría (audit_logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_identifier VARCHAR(150), -- Email de admin, IP o id
    action VARCHAR(100) NOT NULL, -- 'CREATE_PRODUCT', 'DELETE_COUPON', 'UPDATE_SETTINGS'
    table_name VARCHAR(50),
    row_id VARCHAR(100),
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Notificaciones (notifications)
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    read BOOLEAN DEFAULT false,
    alert_type VARCHAR(50) DEFAULT 'info', -- 'info', 'warning', 'success', 'order'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Banners y Sliders Dinámicos (banners)
CREATE TABLE IF NOT EXISTS public.banners (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(150) NOT NULL,
    subtitle VARCHAR(255),
    image_url TEXT NOT NULL,
    link_url VARCHAR(255),
    active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 7. DISPARADORES Y ACTUALIZACIONES AUTOMÁTICAS
-- ==========================================

-- Función auxiliar para refrescar el timestamp updated_at
CREATE OR REPLACE FUNCTION public.update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear disparadores automáticos para actualizarlos al modificar filas
CREATE OR REPLACE TRIGGER update_products_modtime BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();
CREATE OR REPLACE TRIGGER update_categories_modtime BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();
CREATE OR REPLACE TRIGGER update_subcategories_modtime BEFORE UPDATE ON public.subcategories FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();
CREATE OR REPLACE TRIGGER update_users_modtime BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();
CREATE OR REPLACE TRIGGER update_variants_modtime BEFORE UPDATE ON public.product_variants FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();
CREATE OR REPLACE TRIGGER update_orders_modtime BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();

-- ==========================================
-- 8. ÍNDICES DE RENDIMIENTO DE BÚSQUEDA RÁPIDA
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_products_search ON public.products (active, featured, paused);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products (categoria_id, subcategoria_id);
CREATE INDEX IF NOT EXISTS idx_products_codigo ON public.products (codigo) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_variants_product ON public.product_variants (product_id, active);
CREATE INDEX IF NOT EXISTS idx_variants_sku ON public.product_variants (sku) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_orders_user ON public.orders (user_id, current_status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON public.orders (customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON public.order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product ON public.reviews (product_id, approved);
CREATE INDEX IF NOT EXISTS idx_inventory_product ON public.inventory_movements (product_id);

-- ==========================================
-- 9. CONFIGURACIÓN RLS (Row Level Security - Supabase)
-- ==========================================
-- Por defecto habilitamos RLS por seguridad, pero aseguramos acceso público de lectura para el catálogo.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- Políticas de Lectura Pública (Todos pueden navegar el sitio)
DROP POLICY IF EXISTS "Permitir lectura publica de productos" ON public.products;
CREATE POLICY "Permitir lectura publica de productos" ON public.products FOR SELECT USING (active = true AND paused = false);

DROP POLICY IF EXISTS "Permitir lectura publica de categorias" ON public.categories;
CREATE POLICY "Permitir lectura publica de categorias" ON public.categories FOR SELECT USING (active = true);

DROP POLICY IF EXISTS "Permitir lectura publica de subcategorias" ON public.subcategories;
CREATE POLICY "Permitir lectura publica de subcategorias" ON public.subcategories FOR SELECT USING (active = true);

DROP POLICY IF EXISTS "Permitir lectura publica de banners" ON public.banners;
CREATE POLICY "Permitir lectura publica de banners" ON public.banners FOR SELECT USING (active = true);

-- Políticas de Escritura solo para autenticados o administradores (simulación ilustrativa)
DROP POLICY IF EXISTS "Solo administradores pueden modificar productos" ON public.products;
CREATE POLICY "Solo administradores pueden modificar productos" ON public.products FOR ALL TO authenticated USING (true);


-- ============================================================================
-- 10. MIGRACIÓN COMPLEMENTARIA DE SEGURIDAD (ALTER TABLE)
-- ============================================================================
-- Estos comandos garantizan que si ya existen las tablas en tu base de datos,
-- se agregarán de manera segura todas las columnas requeridas por el servidor.
-- ============================================================================

-- Migración de la Tabla de Productos (public.products)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_3d BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS hours_per_unit NUMERIC(10, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS size_chart_enabled BOOLEAN DEFAULT true;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS size_chart_show_superior BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS size_chart_show_inferior BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS size_chart_show_calzado BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS size_chart_show_recommender BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS size_chart_data JSONB;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS consult_only BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS categorias_adicionales TEXT[] DEFAULT '{}';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS subcategorias_adicionales TEXT[] DEFAULT '{}';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS codigo VARCHAR(100);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS precio_compra NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS precio_con_40 NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS comision_ml NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS precio_venta_ml NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS precio_web NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS descuento_porcentaje NUMERIC(10, 2) DEFAULT 0.00;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_pinamar INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_montevideo INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_combo BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS combo_components JSONB DEFAULT '[]';

-- Migración de la Tabla de Variantes (public.product_variants)
ALTER TABLE public.product_variants ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.product_variants ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2);
ALTER TABLE public.product_variants ADD COLUMN IF NOT EXISTS stock_pinamar INTEGER DEFAULT 0;
ALTER TABLE public.product_variants ADD COLUMN IF NOT EXISTS stock_montevideo INTEGER DEFAULT 0;

-- Migración de la Tabla de Pedidos (public.orders)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS deposito_origen VARCHAR(50);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS canal VARCHAR(50);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS bypass_stock_deduction BOOLEAN DEFAULT false;

-- Creación segura de nuevos Índices de Rendimiento complementarios
CREATE INDEX IF NOT EXISTS idx_products_codigo ON public.products (codigo) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_variants_sku ON public.product_variants (sku) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON public.orders (customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders (created_at DESC);
